development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_czech_ci
  database: aa_devel
  username: nis
  password: nis
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_czech_ci
  database: aa_test
  username: nis
  password: nis
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_czech_ci
  database: aa_production
  username: nis
  password: nis
  host: 127.0.0.1
